name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Create coveragerc
        run: |
          cat << EOF > .coveragerc
          [run]
          source = gendiff
          relative_files = True
          EOF

      - name: Run tests with coverage
        run: uv run pytest --cov=gendiff --cov-report=xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Temalllytera_python-project-50
            -Dsonar.organization=temalllytera
            -Dsonar.sources=gendiff
            -Dsonar.tests=tests
            -Dsonar.python.version=3.9
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
